<?php

namespace ContainerYcQJqFx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdminControllerviewCandidatureService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.9MTj4fh.App\Controller\Admin\AdminController::viewCandidature()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.9MTj4fh.App\\Controller\\Admin\\AdminController::viewCandidature()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'candidat' => ['privates', '.errored..service_locator.9MTj4fh.App\\Entity\\Candidat', NULL, 'Cannot autowire service ".service_locator.9MTj4fh": it needs an instance of "App\\Entity\\Candidat" but this type has been excluded in "config/services.yaml".'],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'candidatRepository' => ['privates', 'App\\Repository\\CandidatRepository', 'getCandidatRepositoryService', true],
        ], [
            'candidat' => 'App\\Entity\\Candidat',
            'em' => '?',
            'candidatRepository' => 'App\\Repository\\CandidatRepository',
        ]))->withContext('App\\Controller\\Admin\\AdminController::viewCandidature()', $container);
    }
}
