<?php

namespace ContainerYcQJqFx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCvControllerdownloadCvService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.CRuyhq3.App\Controller\CvController::downloadCv()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.CRuyhq3.App\\Controller\\CvController::downloadCv()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'candidat' => ['privates', '.errored..service_locator.CRuyhq3.App\\Entity\\Candidat', NULL, 'Cannot autowire service ".service_locator.CRuyhq3": it needs an instance of "App\\Entity\\Candidat" but this type has been excluded in "config/services.yaml".'],
        ], [
            'candidat' => 'App\\Entity\\Candidat',
        ]))->withContext('App\\Controller\\CvController::downloadCv()', $container);
    }
}
