vich_uploader:
    db_driver: orm
    mappings:
        job_logos:
            uri_prefix: /uploads/joblogos
            upload_destination: '%kernel.project_dir%/public/uploads/joblogos'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
