<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Job extends \App\Entity\Job implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'activated' => [parent::class, 'activated', null],
        "\0".parent::class."\0".'anneesExperienceRequise' => [parent::class, 'anneesExperienceRequise', null],
        "\0".parent::class."\0".'candidats' => [parent::class, 'candidats', null],
        "\0".parent::class."\0".'category' => [parent::class, 'category', null],
        "\0".parent::class."\0".'company' => [parent::class, 'company', null],
        "\0".parent::class."\0".'competencesRequises' => [parent::class, 'competencesRequises', null],
        "\0".parent::class."\0".'createdAt' => [parent::class, 'createdAt', null],
        "\0".parent::class."\0".'description' => [parent::class, 'description', null],
        "\0".parent::class."\0".'email' => [parent::class, 'email', null],
        "\0".parent::class."\0".'expireAt' => [parent::class, 'expireAt', null],
        "\0".parent::class."\0".'howToApply' => [parent::class, 'howToApply', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'location' => [parent::class, 'location', null],
        "\0".parent::class."\0".'logo' => [parent::class, 'logo', null],
        "\0".parent::class."\0".'logoFile' => [parent::class, 'logoFile', null],
        "\0".parent::class."\0".'position' => [parent::class, 'position', null],
        "\0".parent::class."\0".'public' => [parent::class, 'public', null],
        "\0".parent::class."\0".'token' => [parent::class, 'token', null],
        "\0".parent::class."\0".'type' => [parent::class, 'type', null],
        "\0".parent::class."\0".'updatedAt' => [parent::class, 'updatedAt', null],
        "\0".parent::class."\0".'url' => [parent::class, 'url', null],
        'activated' => [parent::class, 'activated', null],
        'anneesExperienceRequise' => [parent::class, 'anneesExperienceRequise', null],
        'candidats' => [parent::class, 'candidats', null],
        'category' => [parent::class, 'category', null],
        'company' => [parent::class, 'company', null],
        'competencesRequises' => [parent::class, 'competencesRequises', null],
        'createdAt' => [parent::class, 'createdAt', null],
        'description' => [parent::class, 'description', null],
        'email' => [parent::class, 'email', null],
        'expireAt' => [parent::class, 'expireAt', null],
        'howToApply' => [parent::class, 'howToApply', null],
        'id' => [parent::class, 'id', null],
        'location' => [parent::class, 'location', null],
        'logo' => [parent::class, 'logo', null],
        'logoFile' => [parent::class, 'logoFile', null],
        'position' => [parent::class, 'position', null],
        'public' => [parent::class, 'public', null],
        'token' => [parent::class, 'token', null],
        'type' => [parent::class, 'type', null],
        'updatedAt' => [parent::class, 'updatedAt', null],
        'url' => [parent::class, 'url', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
