<?php

namespace ContainerBF1Kike;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSendTestEmailCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'console.command.public_alias.App\Command\App\Command\SendTestEmailCommand' shared autowired service.
     *
     * @return \App\Command\App\Command\SendTestEmailCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'Command.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'App'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'SendTestEmailCommand.php';

        return $container->services['console.command.public_alias.App\\Command\\App\\Command\\SendTestEmailCommand'] = new \App\Command\App\Command\SendTestEmailCommand(($container->privates['mailer.mailer'] ?? $container->load('getMailer_MailerService')));
    }
}
