<?php

namespace ContainerCWzqWea;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdminControllerupdateStatutService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.vSkghii.App\Controller\Admin\AdminController::updateStatut()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.vSkghii.App\\Controller\\Admin\\AdminController::updateStatut()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'candidat' => ['privates', '.errored..service_locator.vSkghii.App\\Entity\\Candidat', NULL, 'Cannot autowire service ".service_locator.vSkghii": it needs an instance of "App\\Entity\\Candidat" but this type has been excluded in "config/services.yaml".'],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'context' => ['privates', '.errored..service_locator.vSkghii.EasyCorp\\Bundle\\EasyAdminBundle\\Context\\AdminContext', NULL, 'Cannot autowire service ".service_locator.vSkghii": it references class "EasyCorp\\Bundle\\EasyAdminBundle\\Context\\AdminContext" but no such service exists.'],
        ], [
            'candidat' => 'App\\Entity\\Candidat',
            'em' => '?',
            'context' => 'EasyCorp\\Bundle\\EasyAdminBundle\\Context\\AdminContext',
        ]))->withContext('App\\Controller\\Admin\\AdminController::updateStatut()', $container);
    }
}
