<?php

namespace ContainerCWzqWea;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCandidat2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.CRuyhq3.App\Entity\Candidat' shared service.
     *
     * @return \App\Entity\Candidat
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.CRuyhq3": it needs an instance of "App\\Entity\\Candidat" but this type has been excluded in "config/services.yaml".');
    }
}
