<?php

namespace ContainerCWzqWea;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getJobControllerapplyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.dlt9PmK.App\Controller\JobController::apply()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.dlt9PmK.App\\Controller\\JobController::apply()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'job' => ['privates', '.errored..service_locator.dlt9PmK.App\\Entity\\Job', NULL, 'Cannot autowire service ".service_locator.dlt9PmK": it needs an instance of "App\\Entity\\Job" but this type has been excluded in "config/services.yaml".'],
        ], [
            'job' => 'App\\Entity\\Job',
        ]))->withContext('App\\Controller\\JobController::apply()', $container);
    }
}
