controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

home :
    path: /
    controller : App\Controller\JobController::index
    
jobs_by_category:
    path: /jobs/category/{category}
    controller: App\Controller\JobController::listByCategory

app_login:
    path: /login
    controller: App\Controller\LoginController::login

app_profile:
    path: /profile
    controller: App\Controller\UserController::profile

list:
    path: /list
    controller: App\Controller\JobController::list

app_cv:
    path: /cv/{id}
    controller: App\Controller\CvController::index

app_logout:
    path: /logout
    methods: POST

easy_admin_bundle:
    path: \admin
    controller: App\Controller\Admin\AdminController::index
