<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYcQJqFx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYcQJqFx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYcQJqFx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYcQJqFx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerYcQJqFx\App_KernelDevDebugContainer([
    'container.build_hash' => 'YcQJqFx',
    'container.build_id' => '5b7538cb',
    'container.build_time' => 1733772830,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYcQJqFx');
